#!/usr/bin/env python
from importlib import import_module
import os
import sys
import ROOT
import math
ROOT.PyConfig.IgnoreCommandLineOptions = True

class eventHistos:
    def __init__(self, directoryName):
   	self.directoryName = directoryName
	self.h_eventcount = ROOT.TH1F(directoryName+'EventCount', 'Event Count', 1, 0, 1)
        self.h_eventweight = ROOT.TH1F(directoryName+'EventWeight', 'Event Weight', 200, -100, 100)
        self.h_fourobjectinvariantmass = ROOT.TH1F(directoryName+'FourObjectInvariantMass', 'Four Object Invariant Mass m_{lljj}', 1600, 0, 8000)
	self.h_q2input = ROOT.TH1F(directoryName+'Q2In', 'Initial q^{2}', 2000, 0, 20000000)
        self.h_q2ZBoson = ROOT.TH1F(directoryName+'Q2Z', 'q^{2}_{Z}', 200, 0, 1000000)
	self.h_q2difference = ROOT.TH1F(directoryName+'Q2Diff', 'q^{2}_{in} - q^{2}_{Z} ', 2000, 0, 20000000)
        self.h_fourobjectinvariantpt = ROOT.TH1F(directoryName+'FourObjectInvariantpT', 'Four Object pT p_{T}(lljj)', 200, 0, 1000)
        self.h_leadjetpt = ROOT.TH1F(directoryName+'LeadJetpT', 'Lead jet p_{T}', 200, 0, 1000)
        self.h_subleadjetpt = ROOT.TH1F(directoryName+'SubleadJetpT', 'Sublead jet p_{T}', 200, 0, 1000)
        self.h_dileppt = ROOT.TH1F(directoryName+'DileptonpT', 'Dilepton p_{T}(ll)', 200, 0, 1000)
        self.h_ptllOvermll = ROOT.TH1F(directoryName+'PtllOverMll', 'p_{T}^{ll}/m_{ll}', 200, 0, 10)
        self.h_dijetpt = ROOT.TH1F(directoryName+'DijetpT', 'Dijet p_{T}(jj)', 200, 0, 1000)
        self.h_dijetmass = ROOT.TH1F(directoryName+'DijetMass', 'Dijet mass m_{jj}', 200, 0, 1000)
	self.h_ptjjOvermjj = ROOT.TH1F(directoryName+'PtjjOverMjj', 'p_{T}^{jj}/m_{jj}', 200, 0, 10)
        self.h_leadjetZmass = ROOT.TH1F(directoryName+'LeadJetZMass', 'Lead Jet + Z Mass m_{jZ}', 400, 0, 2000)
        self.h_subleadjetZmass = ROOT.TH1F(directoryName+'SubleadJetZMass', 'Sublead Jet + Z Mass m_{jZ}', 400, 0, 2000)
        self.h_leadleppt = ROOT.TH1F(directoryName+'LeadLeptonpT', 'Lead Lepton p_{T}', 200, 0, 1000)
        self.h_subleadleppt = ROOT.TH1F(directoryName+'SubleadLeptonpT', 'Sublead Lepton p_{T}', 200, 0, 1000)
        self.h_dilepmass = ROOT.TH1F(directoryName+'DileptonMass', 'Dilepton Mass m_{ll}', 200, 0, 1000)
        self.h_leadjeteta = ROOT.TH1F(directoryName+'LeadJetEta', 'Lead jet #eta', 100, -3, 3)
        self.h_subleadjeteta = ROOT.TH1F(directoryName+'SubleadJetEta', 'Sublead jet #eta', 100, -3, 3)
        self.h_leadjetphi = ROOT.TH1F(directoryName+'LeadJetPhi', 'Lead jet #phi', 100, -4, 4)
        self.h_subleadjetphi = ROOT.TH1F(directoryName+'SubleadJetPhi', 'Sublead jet #phi', 100, -4, 4)
        self.h_leadlepeta = ROOT.TH1F(directoryName+'LeadLeptonEta', 'Lead Lepton #eta', 100, -3, 3)
        self.h_subleadlepeta = ROOT.TH1F(directoryName+'SubleadLeptonEta', 'Sublead Lepton #eta', 100, -3, 3)
        self.h_leadlepphi = ROOT.TH1F(directoryName+'LeadLeptonPhi', 'Lead Lepton #phi', 100, -4, 4)
        self.h_subleadlepphi = ROOT.TH1F(directoryName+'SubleadLeptonPhi', 'Sublead Lepton #phi', 100, -4, 4)

    def eventweights(self, event):
        self.h_eventweight.Fill(event.eventWeight)

    def FillHists(self, event):
	self.h_eventcount.Fill(0.5, event.eventWeight)
        self.h_fourobjectinvariantmass.Fill(event.fourObjectInvariantMass, event.eventWeight)	
        self.h_fourobjectinvariantpt.Fill(event.fourObjectInvariantPt, event.eventWeight)
        self.h_leadjetpt.Fill(event.leadJetPt, event.eventWeight)
        self.h_subleadjetpt.Fill(event.subleadJetPt, event.eventWeight)
        self.h_leadjeteta.Fill(event.leadJetEta, event.eventWeight)
        self.h_subleadjeteta.Fill(event.subleadJetEta, event.eventWeight)
        self.h_leadjetphi.Fill(event.leadJetPhi, event.eventWeight)
        self.h_subleadjetphi.Fill(event.subleadJetPhi, event.eventWeight)
        self.h_dijetmass.Fill(event.diJetMass, event.eventWeight)
        self.h_dijetpt.Fill(event.diJetPt, event.eventWeight)
	self.h_ptjjOvermjj.Fill(event.PtjjOverMjj, event.eventWeight)
        self.h_leadleppt.Fill(event.leadLepPt, event.eventWeight)
        self.h_subleadleppt.Fill(event.subleadLepPt, event.eventWeight)
        self.h_leadlepeta.Fill(event.leadLepEta, event.eventWeight)
        self.h_subleadlepeta.Fill(event.subleadLepEta, event.eventWeight)
        self.h_leadlepphi.Fill(event.leadLepPhi, event.eventWeight)
        self.h_subleadlepphi.Fill(event.subleadLepPhi, event.eventWeight)
        self.h_dilepmass.Fill(event.diLepMass, event.eventWeight)
        self.h_dileppt.Fill(event.diLepPt, event.eventWeight)
        self.h_ptllOvermll.Fill(event.PtllOverMll, event.eventWeight)
        self.h_leadjetZmass.Fill(event.leadJetZMass, event.eventWeight)
        self.h_subleadjetZmass.Fill(event.subleadJetZMass, event.eventWeight)
	self.h_q2input.Fill(event.q2in, event.eventWeight)
        self.h_q2ZBoson.Fill(event.q2Z, event.eventWeight)
        self.h_q2difference.Fill(event.q2diff, event.eventWeight)


    def WriteHists(self):
        self.h_eventweight.Write()
	self.h_eventcount.Write()
	self.h_q2input.Write()
        self.h_q2ZBoson.Write()
        self.h_q2difference.Write()
        self.h_fourobjectinvariantmass.Write()
	self.h_leadjetpt.Write()
        self.h_subleadjetpt.Write()
        self.h_ptllOvermll.Write()
        self.h_ptjjOvermjj.Write()
        self.h_dileppt.Write()
        self.h_leadjetZmass.Write()
        self.h_subleadjetZmass.Write()
        self.h_dijetmass.Write()
        self.h_dijetpt.Write()
        self.h_leadleppt.Write()
        self.h_subleadleppt.Write()
        self.h_dilepmass.Write()
	self.h_fourobjectinvariantpt.Write()
        self.h_leadjeteta.Write()
        self.h_subleadjeteta.Write()
        self.h_leadjetphi.Write()
        self.h_subleadjetphi.Write()
        self.h_leadlepeta.Write()
        self.h_subleadlepeta.Write()
        self.h_leadlepphi.Write()
        self.h_subleadlepphi.Write()
